### PR TITLE
Adding 3 methods on Personnummer; GetYear(), GetMonth() and GetDay().

### PR DESCRIPTION
**Pull request by corgrath**

### CODE REVIEW

**Comment by corgrath** [comment]
I don't have the right to add reviewers, so I am pinging @tike @hwsoderlund @flaviamissi.

**Comment by corgrath** [comment]
This methods will later be used in our Backend code.

**Comment by hwsoderlund** [comment]
I am having trouble seeing the value of adding these methods when it's so easy to just use the Format function on the Birth (time.Time):
```somePersonNummer.Birth.Format("2006")
somePersonNummer.Birth.Format("01")
somePersonNummer.Birth.Format("02")
```

**Comment by corgrath** [comment]
I havent seen that. Will check it out.

**Comment by corgrath** [comment]
That such a quirky system with the reference time. Closing down the PR.

**Comment by hwsoderlund** [comment]
Yeah, it is a bit quirky. But once you have it in your head, it's actually quite convenient. It has grown on me.

**Pull request closed without merging**
